version: "3"

networks:
  q2io-net:
    driver: bridge

services:
  postgres_db:
    image: postgres:latest
    restart: always
    networks:
      - q2io-net
    environment:
      POSTGRES_USER: q2io
      POSTGRES_DB: q2io
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
