name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      with:
        enable-stack: true
        ghc-version: '8.8' # Resolves to the latest point release of GHC 8.8
        stack-version: 'latest'
    - name: Build
      run:  stack build --system-ghc --test

    - name: Run hlint
      run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

    - name: Run Tests
      run: stack test --system-ghc
